apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  labels:
    app: rancher-demo
spec:
  selector:
    matchLabels:
      app: rancher-demo-1  # Match the template metadata labels
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: rancher-demo-1  # Ensure this matches the selector matchLabels
    spec:
      containers:
      - image: salahgo/rancher-demo
        name: rancher-demo-3
        ports:
        - containerPort: 8080
          name: demo-http
